package com.stylish.fancy.text.generator.activities;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.stylish.fancy.text.generator.R;
import com.stylish.fancy.text.generator.adapter.EmoticonsAdapter;

import java.util.ArrayList;

public class EmoticonsActivity extends AppCompatActivity {
    Integer selectedImage, selectedIndex;
    String name;
    ArrayList<String> list;
    ImageView icBackOrMenu;
    TextView toolbarTitle;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_emoticons);

        selectedImage = getIntent().getIntExtra("image", -1);
        name = getIntent().getStringExtra("name");
        selectedIndex = getIntent().getIntExtra("index", -1);
        list = new ArrayList<>();

        icBackOrMenu = findViewById(R.id.icBackOrMenu);
        toolbarTitle = findViewById(R.id.toolbarTitle);
        toolbarTitle.setText(name);

        icBackOrMenu.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                onBackPressed();
            }
        });

        if (selectedIndex != -1) {
            if (selectedIndex == 0) {
                list.add("♥‿♥");
                list.add("★~(◡‿◡✿)");
                list.add("(ノ・ω・)ノ");
                list.add("★~(◡︿◕✿)");
                list.add("♥╣[-_-]╠♥");
                list.add("（⌒_⌒）");
                list.add(">‿‿◕");
                list.add("★~(◡△◕✿)");
                list.add("⎝ᄽ⏝⏠⎠");
                list.add("(~￣▽￣)~");
                list.add("★~(◡﹏⊙✿)");
                list.add("★~(◠﹏◕✿)");
                list.add("(◕‿-)");
                list.add("★~(◡﹏◕✿)");
                list.add("★~(◠﹏⊙✿)");
                list.add("★~(◠ω◕✿)");
                list.add("♥╭╮♥");
                list.add("★~(◡‿⊙✿)");
                list.add("(｡♥‿♥｡)");
                list.add("★~(◡△⊙✿)");
                list.add("★~(◠‿◕✿)");
                list.add("v(=∩_∩=)ﾌ");
                list.add("♥╭╮♥");
                list.add("(ΘεΘ");
                list.add("★~(◡‿◕✿)");
                list.add("★~(◡ω◕✿)");
                list.add("( ^▽^)σ)~O~)");
                list.add("★~(◠△◕✿)");
                list.add("(✿ ♥‿♥)");
                list.add("★~(◠△⊙✿)");
                list.add("(╯3╰)");
                list.add("★~(◠ω⊙✿)");
                list.add("★~(◡△◡✿)");
                list.add("★~(◡﹏◡✿)");
                list.add("(●´ω｀●)");
                list.add("★~(◡︿⊙✿)");
                list.add("☼.☼");
                list.add("★~(◠︿⊙✿)");
                list.add("★~(◡ω◡✿)");
                list.add("ヘ(^_^ヘ)");
                list.add("(n˘v˘•)¬");
                list.add("( ･_･)♡");
                list.add("★~(◡ω⊙✿)");
                list.add("(●♡∀♡)");
                list.add("(｡♥‿♥｡)");
                list.add("(♥ω♥ ) ~♪");
                list.add("(♥ω♥*)");
                list.add("(✿ ♥‿♥)");
                list.add("✿♥‿♥✿");
                list.add("乂❤‿❤乂");
                list.add("٩(♡ε♡ )۶");
                list.add("ლζ*♡ε♡*ζლ");
                list.add("⊂（♡⌂♡）⊃");
                list.add("(๑♡3♡๑)");
                list.add("(๑♡⌓♡๑)");
                list.add("♱♡‿♡♰");
                list.add("⊆♥_㇁♥⊇");
                list.add("(●♡∀♡))ヾ☆*。");
                list.add("໒( ♥ ◡ ♥ )७");
                list.add("༼♥ل͜♥༽");
                list.add("(灬♥ω♥灬)");
                list.add("(‘∀’●)♡");
                list.add("(´∀｀)♡");
                list.add("（*´▽｀*）");
                list.add("（´・｀ ）♡");
                list.add("（´ω｀♡%）");
                list.add("♥(ˆ⌣ˆԅ)");
                list.add("꒰˘̩̩̩⌣˘̩̩̩๑꒱♡");
                list.add("ლ(́◉◞౪◟◉‵ლ)");
                list.add("⸌̷̻( ᷇ॢ〰ॢ ᷆◍)⸌̷̻♡⃛");
                list.add("₍՞◌′ᵕ‵ू◌₎♡");
                list.add("♡ฅ(ᐤˊ꒳ฅˋᐤ♪)");
                list.add("ʚ♡⃛ɞ(ू•ᴗ•ू❁)");
                list.add("❣⃛(❛ั◡˜๑)");
                list.add("( ˭̵̵̵̵͈́◡ु͂˭̵̵̵͈̀ )ˉ̞̭♡");
                list.add("♡(ŐωŐ人)");
                list.add("❤⃛ヾ(๑❛ ▿ ◠๑ )");
                list.add("（*’∀’人）♥");
                list.add("(°◡°♡).:｡");
                list.add("ʸ(➜◡ु⚈᷉)♡⃛");
                list.add("ˉ̞̭(′͈∨‵͈♡)˄̻ ̊");
                list.add("◟(◔ั₀◔ั )◞ ༘♡");
                list.add("φ(ﾟ ωﾟ//）♡");
                list.add("ʸ(ᴖ́◡ु⚈᷉)♡⃛");
                list.add("ꉂ (′̤ॢ∀ ू‵̤๑))ˉ̞̭♡");
                list.add("♡♡+.ﾟ(￫ε￩*)ﾟ+.ﾟ");
                list.add("꒰✪ૢꇵ✪ૢ꒱ෆ⃛");
                list.add("(●´□`)♡");
                list.add("(｡･ω･｡)ﾉ♡");
                list.add("(｡’▽’｡)♡");
                list.add("（●´∀｀）ノ♡");
                list.add("₍₍ ( ๑॔˃̶◡ ˂̶๑॓)◞♡");
                list.add("(๑・ω-)～♥”");
                list.add("(๑°꒵°๑)･*♡");
                list.add("～(^з^)-♡");
                list.add("(๑ˊ͈ ॢꇴ ˋ͈)〜♡॰ॱ");
                list.add("(ෆ ͒•∘̬• ͒)◞");
                list.add("♡(㋭ ਊ ㋲)♡");
                list.add("( •ॢ◡-ॢ)-♡");
                list.add("(●’ᴗ’σ)σணღ*");
            } else if (selectedIndex == 1) {
                list.add("(◕‿◕✿)");
                list.add("(◠‿◠✿)");
                list.add("(◠﹏◠✿)");
                list.add("（＊＾Ｕ＾）人（≧Ｖ≦＊）/");
                list.add("ôヮô");
                list.add("∧( ‘Θ’ )∧");
                list.add("(¤﹏¤)");
                list.add("●‿●");
                list.add("ʕ·ᴥ·ʔ");
                list.add("＼（＾○＾）人（＾○＾）／");
                list.add("ヾ(＠⌒▽⌒＠)ﾉ");
                list.add("(°∀°)");
                list.add("ヾ｜￣ー￣｜ﾉ");
                list.add("(☉‿☉✿)");
                list.add("┏(＾0＾)┛┗(＾0＾) ┓");
                list.add("(◡‿◡✿)");
                list.add("✿◕ ‿ ◕✿");
                list.add("ヽ(‘ ∇‘ )ノ");
                list.add("☆(❁‿❁)☆");
                list.add("❀◕ ‿ ◕❀");
                list.add("ヽ(^◇^*)/");
                list.add("(•⊙ω⊙•)");
                list.add("!⑈ˆ~ˆ!⑈");
                list.add("(*^ -^*)");
                list.add("(⊙‿⊙✿)");
                list.add("◕3◕");
                list.add("(ﾟヮﾟ)");
                list.add("¢‿¢");
                list.add("ヅ");
                list.add("●ᴥ●");
                list.add("(∪ ◡ ∪)");
                list.add("≖‿≖");
                list.add("≧◡≦");
                list.add("٩◔‿◔۶");
                list.add("｡◕ ‿ ◕｡");
                list.add("ヾ(＠＾▽＾＠)ﾉ");
                list.add("◃┆◉◡◉┆▷");
                list.add("(✿◠‿◠)");
                list.add("(￣ｰ￣)");
                list.add("╰(◡‿◡✿╰)");
                list.add("~,~");
                list.add("(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧");
                list.add("(*~▽~)");
                list.add("❀‿❀");
                list.add("◕‿◕");
                list.add("(^L^)");
                list.add("(^▽^)");
                list.add("◕ ◡ ◕");
                list.add("(◕‿◕✿)");
                list.add("（ ；´Д｀）");
                list.add("⊙﹏⊙");
                list.add("✿｡✿");
                list.add("ヽ(゜∇゜)ノ");
                list.add("｡(✿‿✿)｡");
                list.add("(´ー｀)");
                list.add("ツ");
                list.add("q(❂‿❂)p");
                list.add("( ́ ◕◞ε◟◕`)");
                list.add("☆(◒‿◒)☆");
                list.add("(∩▂∩)");
                list.add("(¬‿¬)");
                list.add("(^Ｏ^)");
                list.add("ʘ‿ʘ");
                list.add("（’◎’）");
                list.add("(◜௰◝)");
                list.add("(^ｰ^)");
                list.add("(o´ω｀o)");
                list.add("(^з^)-☆");
                list.add("(◕ω◕✿)");
                list.add("(づ｡◕‿‿◕｡)づ");
                list.add("(ﾟ▽^*)");
                list.add("(⌒o⌒)");
                list.add("(｡◕‿◕｡)");
                list.add("ت");
                list.add("(. ﾟーﾟ)");
                list.add("१✌˚◡˚✌५");
                list.add("＼(●~▽~●)");
                list.add("(*˘︶˘*)");
                list.add("(✪㉨✪)");
                list.add("(ᅌᴗᅌ* )");
                list.add("^L^");
                list.add("(･ｪ-)");
                list.add("＼(*^▽^*)/");
                list.add("(◠△◠✿)");
                list.add("( ಠ◡ಠ )");
                list.add("(〃^∇^)ﾉ");
                list.add("^^");
                list.add("|◔◡◉|");
                list.add("(●⌒∇⌒●)");
                list.add("⊂◉‿◉つ");
                list.add(".ʕʘ‿ʘʔ.");
                list.add("(*・∀・*)人(*・∀・*)");
                list.add("＼(^-^)／");
                list.add("∩(︶▽︶)∩");
                list.add("（☉∀☉）");
                list.add("(´ω｀)");
                list.add("●﹏●");
                list.add("（ ´∀｀）☆");
                list.add("•ᴥ•");
                list.add("✿◕ ‿ ◕✿");
            } else if (selectedIndex == 2) {
                list.add("ヾ(´〇`)ﾉ♪♪♪");
                list.add("ヘ(￣ω￣ヘ)");
                list.add("(〜￣▽￣)〜");
                list.add("〜(￣▽￣〜)");
                list.add("ヽ(o´∀`)ﾉ♪♬");
                list.add("(ﾉ≧∀≦)ﾉ");
                list.add("♪ヽ(^^ヽ)♪");
                list.add("♪(/_ _ )/♪");
                list.add("♪♬((d⌒ω⌒b))♬♪");
                list.add("└(￣-￣└))");
                list.add("((┘￣ω￣)┘");
                list.add("√(￣‥￣√)");
                list.add("└(＾＾)┐");
                list.add("┌(＾＾)┘");
                list.add("＼(￣▽￣)＼");
                list.add("／(￣▽￣)／");
                list.add("(￣▽￣)/♫•*¨*•.¸¸♪");
                list.add("(^_^♪)");
                list.add("(~˘▽˘)~");
                list.add("~(˘▽˘~)");
                list.add("ヾ(⌐■_■)ノ♪");
                list.add("(〜￣△￣)〜");
                list.add("(~‾▽‾)~");
                list.add("~(˘▽˘)~");
                list.add("乁( • ω •乁)");
                list.add("(｢• ω •)｢");
                list.add("⁽⁽◝( • ω • )◜⁾⁾");
                list.add("✺◟( • ω • )◞✺");
                list.add("♬♫♪◖(● o ●)◗♪♫♬");
                list.add("( ˘ ɜ˘) ♬♪♫");
                list.add("♪♪♪ ヽ(ˇ∀ˇ )ゞ");
                list.add("(o・★)");
                list.add("(☆￢o)q");
                list.add("(^_^♪)");
                list.add("(´△｀)♪");
                list.add("ρ(o＜★)");
                list.add("ρ(o＾★)");
                list.add("(☆￣o)q");
                list.add("(☆∩o)q");
                list.add("(☆≧o)q");
                list.add("(☆Θo)q");
                list.add("(´0｀)q");
                list.add("ρ(oμ★)");
                list.add("（＾Ｏ＾☆♪");
                list.add("（＾3＾）~♪");
                list.add("（*´▽｀*）");
                list.add("ρ（ーoー)♪");
                list.add("（^Ｏ^）～♪");
                list.add("ρ(o δ★)");
                list.add("ρ(＾o^)♪");
                list.add("ρ（^o^）♪");
                list.add("ρ（＾o＾）♪");
                list.add("♫꒰･◡･๑꒱");
                list.add("(o^^o)♪");
                list.add("♫♪˙‿˙♫♪");
                list.add("♪(ﾉε｀●)");
                list.add("ρ(^^ )♭");
                list.add("♪～(￣ε￣)");
                list.add("♪(´ε｀ )");
                list.add("（＊＾ω＾）♪");
                list.add("≧(´▽｀)≦");
            } else if (selectedIndex == 3) {
                //u().r("Animals");
                list.add("(^^ゞ");
                list.add("(〃▽〃)");
                list.add("(ノ▽〃)");
                list.add("（/｡＼)");
                list.add("(/ω＼)");
                list.add("(Ŏ艸Ŏ)");
                list.add("(^^;)");
                list.add("(〃ー〃)");
                list.add("(〃ω〃)");
                list.add("(〃艸〃)");
                list.add("(´つヮ⊂)");
                list.add("(♡´艸`)");
                list.add("(／≧ω＼)");
                list.add("ʕ*ﾉᴥﾉʔ");
                list.add("(/へ＼*)");
                list.add("(*ﾉ▽ﾉ)");
                list.add("(*ﾉωﾉ)");
                list.add("(*ﾉдﾉ)");
                list.add("(´～｀ヾ)");
                list.add("(ﾉ∇≦*)");
                list.add("(‘-’*)");
                list.add("(^◇^；)");
                list.add("|▽//)ゝ");
                list.add("(〃´∀｀)");
                list.add("ꈍ .̮ ꈍ");
                list.add("(〃∀〃)ゞ");
                list.add("( 〃．．)");
                list.add("(｡･･｡)");
                list.add("|´∀｀●)");
                list.add("((-ω-｡)(｡-ω-))");
                list.add("ＯＴＬ");
                list.add("ｏｒｚ");
                list.add("＿ﾉフ○");
                list.add("(￣Д￣");
                list.add("(´Д⊂");
                list.add("（－－；");
                list.add("（´。｀)");
                list.add("（￣Ω￣）");
                list.add("(A´Å｀");
                list.add("A^-^)");
                list.add("(∋д∈)");
                list.add("(・。-;");
                list.add("（´・｀）");
                list.add("(*Q*)");
                list.add("(／０￣)");
                list.add("＿|￣|○");
                list.add("(-。-;");
                list.add("(´Д｀)");
                list.add("(;´Д｀)");
                list.add("（＾。＾；）");
                list.add("(≧∀≦ゞ");
                list.add("(-ω-ゞ");
                list.add("(≧ω≦)ゞ");
                list.add("(｀-´)>");
                list.add("∠(｀∪´)");
                list.add("|`Д´)＞");
                list.add("(≧∇≦)b");
                list.add("(・∀-d)");
                list.add("(`Д´)ゞ");
                list.add("|▼皿▼)b");
                list.add("(・∧‐)ゞ");
                list.add("(●・ω・)b");
                list.add("ｄ(´▽｀*)");
                list.add("(*゜－＾)ゞ");
                list.add("(°∀°)ゝ”");
                list.add("(*｀Ω´)b");
                list.add("(＞Д＜)ゝ”");
                list.add("(=ﾟ▽ﾟ)/");
                list.add("('∀`)ゝ”");
                list.add("( ｀д´)b");
                list.add("d(￣▽￣o)");
                list.add("(*>ω<)b");
                list.add("(｀∀´)ゝ”");
                list.add("d(´･ω･`)");
                list.add("(*´ω｀*)ノ");
                list.add("(★´ω｀★)ゞ");
                list.add("(●´･∀･)b");
                list.add("d(*ﾟーﾟ*)");
                list.add("☆(･ω･*)ゞ");
                list.add("(●⌒∇⌒●)b");
                list.add("((´д｀))");
                list.add("((；ﾟДﾟ)");
                list.add("((;ﾟДﾟ))");
                list.add("(llФｗФ｀)");
                list.add("((ﾟДﾟ；))");
                list.add("((；ﾟェﾟ；))");
                list.add(":(´◦ω◦｀):");
                list.add("(((＾ω＾)))");
                list.add("（（（゜Д゜；）））");
                list.add("（（（・×・；）））");
                list.add("(((･Α･川)))");
                list.add("((( ；ﾟДﾟ)))");
                list.add("((,,´Θ`,,))");
                list.add("((o(´∀｀)o))");
                list.add("《《(ﾟc_ﾟ；)》》");
                list.add(":;(∩´﹏`∩);:");
                list.add("((((；ﾟДﾟ)))");
                list.add("||lll´Д｀)))");
                list.add("((((；ﾟДﾟ))))");
                list.add("((ﾟﾟ((Д))ﾟﾟ))");
            } else if (selectedIndex == 4) {
                list.add("凸(｀0´)凸");
                list.add("凸ಠ益ಠ)凸");
                list.add("凸(⊙▂⊙✖ )");
                list.add("┌П┐(►˛◄’!)");
                list.add("凸(-0-メ)");
                list.add("凸(｀⌒´メ)凸");
                list.add("凸(｀△´＋）");
                list.add("( ︶︿︶)_╭∩╮");
                list.add("凸(｀ι _´メ）");
                list.add("凸(>皿<)凸");
                list.add("凸(^▼ｪ▼ﾒ^)");
                list.add("t(=n=)");
                list.add("t(- n -)t");
                list.add("凸(¬‿¬)");
                list.add("┌∩┐(◣_◢)┌∩┐");
                list.add("┌∩┐(ಠ_ಠ)┌∩┐");
                list.add("╭∩╮(︶︿︶)╭∩╮");
                list.add("╭∩╮(-_-)╭∩╮");
                list.add("( ≧Д≦)");
                list.add("(；￣Д￣）");
                list.add("(;¬_¬)");
                list.add("（；¬＿¬)");
                list.add("(｡+･`ω･´)");
                list.add("｡゜(｀Д´)゜｡");
                list.add("(　ﾟДﾟ)＜!!");
                list.add("(‡▼益▼)");
                list.add("(,,#ﾟДﾟ)");
                list.add("(҂⌣̀_⌣́)");
                list.add("(；¬д¬)");
                list.add("（;≧皿≦）");
                list.add("(╬ﾟ◥益◤ﾟ)");
                list.add("(╬⓪益⓪)");
                list.add("[○･｀Д´･○]");
                list.add("૮( ᵒ̌▱๋ᵒ̌ )ა");
                list.add("(⁎˃ᆺ˂)");
                list.add("(ꐦ°᷄д°᷅)");
                list.add("((╬●∀●)");
                list.add("(╬ Ò ‸ Ó)");
                list.add("( >д<)");
                list.add("(*｀益´*)");
                list.add("(☞◣д◢)☞");
                list.add("<(｀^´)>");
                list.add("(;｀O´)o");
                list.add("(ꐦ ಠ皿ಠ )");
                list.add("（｀Δ´）！");
                list.add("(*｀Ω´*)");
                list.add("(╬ಠ益ಠ)");
                list.add("(╬ﾟ◥益◤ﾟ) ╬ﾟ");
                list.add("(ு⁎ு)྆྆");
                list.add("(╬⓪益⓪)");
                list.add("（╬ಠ益ಠ)");
                list.add("(●o≧д≦)o");
                list.add("=͟͟͞͞( •̀д•́)))");
                list.add("(๑･`▱´･๑)");
                list.add("༼ つ ͠° ͟ ͟ʖ ͡° ༽つ");
                list.add("(☄ฺ◣д◢)☄ฺ");
                list.add("ꀯ(‴ꑒ᷅⺫ꑒ᷄)");
                list.add("(#｀皿´)");
                list.add("(｀Д´)");
                list.add("(ﾒﾟ皿ﾟ)");
                list.add("(o｀ﾟ皿ﾟ)");
                list.add("( ╬◣ 益◢)");
                list.add("（╬ಠ益ಠ)");
                list.add("（♯▼皿▼）");
                list.add("( ╬◣ 益◢）y━･~");
                list.add("（○｀Ｏ´○）");
                list.add("(; ･`д･´)");
                list.add("｜。｀＞Д＜｜");
                list.add("(; ･`д･´)​");
                list.add("( •̀ω•́ )σ");
                list.add("o(-`д´- ｡)");
                list.add("(´･益･｀*)");
                list.add("(´Д｀)");
                list.add("(¬д¬。)");
                list.add("（≧▼≦；)");
                list.add("(ᇂ∀ᇂ╬)");
                list.add("(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू)");
                list.add("(ू˃̣̣̣̣̣̣o˂̣̣̣̣̣̣ ू)⁼³₌₃");
                list.add("（▼へ▼メ）");
                list.add("｢(#Φ益 Φo)∩");
                list.add("s(・｀ヘ´・；)");
                list.add("s(・｀ヘ´・;)ゞ");
                list.add("Σ(-`Д´-ﾉ；)ﾉ");
                list.add("Σ(▼□▼メ)");
                list.add("๛∙᷅῞ॄ∙᷄");
                list.add("(°ㅂ° ╬)");
                list.add("( ｰ̀εｰ́ )");
                list.add("(눈_눈)");
                list.add("(´◣д◢`+)");
                list.add("(ʘ言ʘ╬)");
                list.add("(Ò 皿 Ó ╬)");
                list.add("(-̀◞८̯◟-́)");
                list.add("( ͒˃⌂˂ ͒)");
                list.add("┌(▀Ĺ̯ ▀-͠ )┐");
                list.add("[⑇⨀ེ⌓⨀ེ•⑇]");
                list.add("Σ(ﾟд´;ﾉ)ﾉ");
                list.add("(-̀◞▥◟-́)");
                list.add("☜(`o´)");
                list.add("(◎益◎;)");
                list.add("(@益@ .:;)");
            } else if (selectedIndex == 5) {
                list.add("ಥ_ಥ");
                list.add("(-’๏_๏’-)");
                list.add("˚⌇˚");
                list.add("o(╥﹏╥)o");
                list.add("(⊙﹏⊙✿)");
                list.add("●︿●");
                list.add("(一。一;;）");
                list.add("(╯︵╰,)");
                list.add("(︶︹︺)");
                list.add("(◡﹏◡✿)");
                list.add("(✖﹏✖)");
                list.add("‘︿’");
                list.add("v( ‘.’ )v");
                list.add("◄.►");
                list.add("(ㄒoㄒ)");
                list.add("⊙︿⊙");
                list.add("(◕︿◕✿)");
                list.add("ਉ_ਉ");
                list.add("┐(‘～`；)┌");
                list.add("(︶︹︺)");
                list.add("흫_흫");
                list.add("ب_ب");
                list.add("╮(─▽─)╭");
                list.add("ಥ‿ಥ");
                list.add("(-’_’-)");
                list.add("(╥╥)");
                list.add("(•̪●)");
                list.add("(∩︵∩)");
                list.add("(o_-)");
                list.add("(｡-_-｡)");
                list.add("(╯_╰)");
                list.add("(╥_╥)");
                list.add("v(ಥ ̯ ಥ)v");
                list.add("<('.'<)");
                list.add("ಠ,ಥ");
                list.add("(◕︵◕)");
                list.add("(´ヘ｀()");
                list.add("(✖╭╮✖)");
                list.add("(◕﹏◕✿)");
                list.add("(+_+)");
                list.add("★~(◠︿◕✿)");
                list.add("(*´д｀*)");
                list.add("(◡△◡✿)");
                list.add("٩(×̯×)۶");
                list.add("(ノ_・。)");
                list.add("┐(‘～`；)┌");
                list.add("(つд｀)");
                list.add("(✖╭╮✖)");
                list.add("ಥ⌣ಥ");
                list.add("இ_இ");
                list.add("✖‿✖");
                list.add("( ≧Д≦)");
                list.add("((´д｀))");
                list.add("(∩︵∩)");
                list.add("(▰˘︹˘▰)");
                list.add("(✖╭╮✖)");
                list.add("(‘A`)");
                list.add("(︶︹︺)");
                list.add("(＠´＿｀＠)");
                list.add("（´＿｀）");
                list.add("(⊙︿⊙✿)");
                list.add("(⌣_⌣”)");
                list.add("(▰︶︹︺▰)");
                list.add("~(｡☉︵ ಠ@)>");
                list.add("⊙︿⊙");
                list.add("ヽ(●ﾟ´Д｀ﾟ●)ﾉﾟ");
                list.add("(.﹒︣︿﹒︣.)");
                list.add("(Θ︹Θ)ს");
                list.add("٩꒰´·⌢•｀꒱۶⁼³₌₃");
                list.add(":: ˓(ᑊᘩᑊ⁎) ::");
                list.add("˓˓(ᑊᘩᑊ⁎)");
                list.add("(๑◕︵◕๑)");
                list.add("( .. )");
                list.add("(｡•́︿•̀｡)");
                list.add("(´°ω°`)");
                list.add("੨( ･᷄ ︵･᷅ )ｼ");
                list.add("꒰๑˃͈꒳˂͈๑꒱ﾉ*ﾞ̥");
                list.add("(⌯˃̶᷄ ﹏ ˂̶᷄⌯)ﾟ");
                list.add("(っ- ‸ – ς)");
                list.add("(๑′°︿°๑)");
                list.add("⊛ठ̯⊛");
                list.add("ಠ╭╮ಠ");
                list.add("( ◞᷄દ◟᷅ )");
                list.add("(oꆤ︵ꆤo)");
                list.add("ಗಾ ﹏ ಗಾ");
                list.add("ᵟຶᴖ ᵟຶ");
                list.add("(⋅⃘˕̭⋅⃘)");
                list.add("ōۃō");
                list.add("( ⁍᷄⌢̻⁍᷅ )");
                list.add("(.﹒︠₋﹒︡.)");
                list.add("(˵¯͒⌢͗¯͒˵)");
                list.add("☹ै");
                list.add("(　´_ﾉ` )");
                list.add("ʕ ಡ ﹏ ಡ ʔ");
                list.add("●︿●");
                list.add("(◕︿◕✿)");
                list.add("ਉ_ਉ");
                list.add("༶ඬ༝ඬ༶");
                list.add("(;-_-)/");
                list.add("(oT-T)尸");
            } else if (selectedIndex == 6) {
                list.add("[(－－)]..zzZ");
                list.add("(－_－) zzZ");
                list.add("(∪｡∪)｡｡｡zzZ");
                list.add("(－ω－) zzZ");
                list.add("(￣o￣) zzZZzzZZ");
                list.add("(( _ _ ))..zzzZZ");
                list.add("(￣ρ￣)..zzZZ");
                list.add("(－.－)...zzz");
                list.add("(＿ ＿*) Z z z");
                list.add("(x . x) ~~zzZ");
                list.add("【:εω");
                list.add("(冫༵、)");
                list.add("(ᴗ˳ᴗ)");
                list.add("(´～`)");
                list.add("( ⓥωⓥ)");
                list.add("(:˒[￣]");
                list.add("(*-ω-)");
                list.add("(︶｡︶✽)");
                list.add("(:3ぅ　)");
                list.add("(¦ꒉ[▓▓]");
                list.add("(¦ꀦ[▓▓]");
                list.add("⌈▓͟⌉ꆟ)ꍞ");
                list.add("（;´_ヘ;）");
                list.add("（´○｀）～ゝ");
                list.add("(¦ꃎ[▓▓]");
                list.add("(¦ꎌ[▓▓]");
                list.add("(¦ꃆ[▓▓]");
                list.add("(¦ꄰ[▓▓]");
                list.add("⌈▒͟⌉ꅼ)ꍞ");
                list.add("＼（´Ｏ｀）／");
                list.add("（◎´〇｀◎）");
                list.add("(´-εヾ )");
                list.add("(｡し_し｡)");
                list.add("(｡´-д-)");
                list.add("(*´ο`*)");
                list.add("川｡μ_μ)σ");
                list.add("(｡v_v｡)");
                list.add("(๑ᵕ⌓ᵕ̤)");
                list.add("(¦ꃩ[▓▓]");
                list.add("꒰◍ᐡᐤᐡ◍꒱");
            } else if (selectedIndex == 7) {
                //u().r("Excited");
                list.add("≧ω≦");
                list.add("୧⍢⃝୨");
                list.add("(⊙ᗜ⊙)");
                list.add("โ๏∀๏ใ");
                list.add("(≧∀≦)");
                list.add("۹⌤_⌤۹");
                list.add("୧☉□☉୨");
                list.add("(⊙ꇴ⊙)");
                list.add("(´∀`)");
                list.add("（・ｗ・）");
                list.add("(ᗒᗨᗕ)");
                list.add("ʘ ͜ʖ ʘ");
                list.add("(≧∇≦*)");
                list.add("(*≧▽≦)");
                list.add("۹(ÒہÓ)۶");
                list.add("(ﾉ･ｪ･)ﾉ");
                list.add("٩(^ᴗ^)۶");
                list.add("б（＞ε＜）∂");
                list.add("(⌬̀⌄⌬́)");
                list.add("٩(θ‿θ)۶");
                list.add("ヽ(＾Д＾)ﾉ");
                list.add("(★^O^★)");
                list.add("（๑✧∀✧๑）");
                list.add("(*≧∀≦*)");
                list.add("٩(●ᴗ●)۶");
                list.add("⸍⚙̥ꇴ⚙̥⸌");
                list.add("(๑>ᴗ<๑)");
                list.add("۹(˒௰˓)۶");
                list.add("(* >ω<)");
                list.add("＼（Ｔ∇Ｔ）／");
            } else if (selectedIndex == 8) {
                list.add("―●○◎-");
                list.add("―⊂ZZZ⊃");
                list.add("（￣ｗ￣）Ψ");
                list.add("◥█̆̈◤࿉∥");
                list.add("(＾-＾)＿日");
                list.add("(。・・)_且");
                list.add("(＃´ー´)旦");
                list.add("且_(・_・ )");
                list.add("(　ﾟДﾟ)⊃旦");
                list.add("( -_-)旦~");
                list.add("(*^◇^)_旦");
                list.add("(*･∀･)_Ω~");
                list.add("~旦_(^O^ )");
                list.add("(　 ゜Д゜)⊃旦");
                list.add("~~旦⊂(･∀･ )");
                list.add("ｰ( ￣▽)_皿~~");
                list.add("(*｀▽´)_旦~~");
                list.add("~~旦_(･o･;)");
                list.add("~(=^‥^)_旦~");
                list.add("且_(ﾟ◇ﾟ；)ノﾞ");
                list.add("(*´ｪ｀*)っ旦~");
                list.add("( ・・)つ-●●●");
                list.add("( ^-^)_旦””");
                list.add("((((´∀｀)＿旦～");
                list.add("( ´･ω･`)_且~");
                list.add("(*´-ω)o旦~┏┓");
                list.add("(*´・ω)o旦~┏┓");
                list.add("~~匸Pヽ(･ω･｀)");
                list.add("(○^ω^)_旦~~♪");
                list.add("~~旦_(-ω-｀｡)");
            } else if (selectedIndex == 9) {
                list.add("(^^ゞ");
                list.add("(〃▽〃)");
                list.add("(ノ▽〃)");
                list.add("（/｡＼)");
                list.add("(/ω＼)");
                list.add("(Ŏ艸Ŏ)");
                list.add("(^^;)");
                list.add("(〃ー〃)");
                list.add("(〃ω〃)");
                list.add("(〃艸〃)");
                list.add("(´つヮ⊂)");
                list.add("(♡´艸`)");
                list.add("(／≧ω＼)");
                list.add("ʕ*ﾉᴥﾉʔ");
                list.add("(/へ＼*)");
                list.add("(*ﾉ▽ﾉ)");
                list.add("(*ﾉωﾉ)");
                list.add("(*ﾉдﾉ)");
                list.add("(´～｀ヾ)");
                list.add("(ﾉ∇≦*)");
                list.add("(‘-’*)");
                list.add("(^◇^；)");
                list.add("|▽//)ゝ");
                list.add("(〃´∀｀)");
                list.add("ꈍ .̮ ꈍ");
                list.add("(〃∀〃)ゞ");
                list.add("( 〃．．)");
                list.add("(｡･･｡)");
                list.add("|´∀｀●)");
            } else if (selectedIndex == 10) {
                list.add("( ͡ຈ╭͜ʖ╮͡ຈ )");
                list.add("( ͡ಠ ʖ̯ ͡ಠ)");
                list.add("( ͡~ ͜ʖ ͡~)");
                list.add("( ͡~ ͜ʖ ͡°)");
                list.add("( ͠° ͟ʖ ͡°)");
                list.add("( ͡ʘ╭͜ʖ╮͡ʘ)");
                list.add("( ͝סּ ͜ʖ͡סּ)");
                list.add("( ͡ᵔ ͜ʖ ͡ᵔ )");
                list.add("( ͡^ ͜ʖ ͡^ )");
                list.add("[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]");
                list.add("( ͡ຈ ͜ʖ ͡ຈ)");
                list.add("( ͡° ʖ̯ ͡°)");
                list.add("( ͡ ͜ʖ ͡ )");
                list.add("(☞ ͡° ͜ʖ ͡°)☞");
                list.add("ᕕ( ͡° ͜ʖ ͡° )ᕗ");
                list.add("( ͡° ͜ʖ ͡°)");
                list.add("( ͡°╭͜ʖ╮͡° )");
                list.add("(つ ͡° ͜ʖ ͡°)つ");
                list.add("( ͡⚆ ͜ʖ ͡⚆)");
                list.add("˓˓ ू༼ ⠁⃘ཀ ⠁⃘ू༽");
                list.add("(▀ ͜ʖ ͡°)");
                list.add("༼ ºل͟º ༽");
                list.add("┌༼ຈل͜ຈ༽┐");
                list.add("༼ ಠل͟ಠ༽");
                list.add("୧༼ ͡◉ل͜ ͡◉༽୨");
                list.add("ヽ༼ ಠ益ಠ ༽ﾉ");
                list.add("༼ ༎ຶ ෴ ༎ຶ༽");
                list.add("༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽");
                list.add("༼･ิɷ･ิ༽");
                list.add("༼ ͒ ̶ ͒༽");
                list.add("༼༼;; ;°;ਊ°;༽");
                list.add("༼( ⁍ืེ – ⁍ื༽༽");
                list.add("༼•͟ ͜ •༽");
                list.add("༼•̃͡ ɷ•̃͡༽");
                list.add("༼ ͒ ͓ ͒༽");
                list.add("༼༭ຶཬ༤ຶ༽");
                list.add("༼ꉺˇɷˇꉺ༽");
                list.add("༼இɷஇ༽");
                list.add("༼✷ɷ✷༽");
                list.add("༼ԾɷԾ༽");
                list.add("༼≖ɷ≖༽");
                list.add("༼ꉺ✺ꉺ༽");
                list.add("༼ꉺლꉺ༽");
                list.add("ヽ༼ຈل͜ຈ༽ﾉ");
                list.add("༼ꉺ౪ꉺ༽");
                list.add("༼ꉺεꉺ༽");
                list.add("༼;´༎ຶ ༎ຶ ༽");
                list.add("༼⁰o⁰；༽");
                list.add("༼(⁽͇ˊ̑⁾ ἴृ ⁽ˋ̑⁾͇)༽");
                list.add("˓ ू༼ ்ͦ॔ཀ ்ͦ॓ू༽");
                list.add("༼ ु ்ͦ॔ཫ ்ͦ॓༽ु˒˒");
                list.add("／༼ ༏༏ີཻ༾ﾍ ༏༏ີཻ༾༾༽༽");
                list.add("༼ ்ͦ॔ཫ ்ͦ॓༽");
                list.add("༼ᶿ᷇ཫᶿ᷆༽");
                list.add("༼  ऀืົཀ  ऀืົ༽");
                list.add("༼՟ິͫཀ՟ິͫ༽");
                list.add("ˋ̧̧̖⁽⁽༼ ु˳̮̑̈༽ु⁾⁾ˋ̧̧̖♪");
                list.add("༼❁ɷ❁༽");
                list.add("༼ ຶཽཀ ຶཽ༽");
                list.add("ヽ༼၀-၀༽ﾉ");
                list.add("༼(❛)㇁(❛)༽");
                list.add("ヽ༼⊙_⊙༽ﾉ");
                list.add("༼⺤`皿′⺤༽");
                list.add("ヽ༼࿃っ࿃༽ﾉ");
                list.add("༼⌐■ل͟■༽");
                list.add("༼ง=ಠ益ಠ=༽ง");
                list.add("╰༼=ಠਊಠ=༽╯");
                list.add("ᕙ༼*◕_◕*༽ᕤ");
                list.add("ヽ༼ಢ_ಢ༽ﾉ");
                list.add("ヽ༼ ʘ̚ل͜ʘ̚༼◕_◕༽◉_◔ ༽ﾉ");
                list.add("┌༼ ⊘ _ ⊘ ༽┐");
                list.add("༼ : ౦ ‸ ౦ : ༽");
                list.add("༼∗ღ۝ღ∗༽");
                list.add("༼ง ͠ຈ ͟ل͜ ͠ຈ༽o:[]:::::::>");
                list.add("༼ᕗຈل͜ຈ༽ᕗ");
                list.add("ヽ༼ຈل͜ರೃ༽ﾉ");
                list.add("ヽヽ༼༼ຈຈل͜ل͜ຈຈ༽༽ﾉﾉ");
                list.add("༼ ᕤ◕◡◕ ༽ᕤ");
                list.add("ᕙ༼˵͠ ͠°ل͜͠ ͠°˵༽ᕗ");
                list.add("ᕦ༼::ಥ෴ಠೃ::༽ノ");
                list.add("༼ •̀ ں •́ ༽");
                list.add("♫ ┌༼ຈل͜ຈ༽┘ ♪");
                list.add("༼ ಥل͟ಥ ༽");
                list.add("༼ﾉƟ͆ل͜Ɵ͆༽ﾉ");
                list.add("༼୨Ɵ͆ل͜Ɵ͆༽୨");
                list.add("ヽ༼Ɵ͆ل͜Ɵ͆ヽ༽");
                list.add("୧༼Ɵ͆ل͜Ɵ͆୧༽");
                list.add("┌༼ຈل͜ຈ༽┘");
                list.add("へ༼ ✪ Ĺ̯ ✪ ༽و");
                list.add("c༼ ͡° ͜ʖ ͡° ༽⊃");
                list.add("༼ ಠ ͟ʖ ಠ ༽");
                list.add("୧༼ ” ✖ ‸ ✖ ” ༽୨");
                list.add("Ѱζ༼ᴼل͜ᴼ༽ᶘѰ");
                list.add("┏༼ ◉ ╭╮ ◉༽┓");
                list.add("ヽ༼ ☯‿☯༼ ಠ益ಠ༽◕ل͜◕༽つ");
                list.add("└༼ •́ ͜ʖ •̀ ༽┘");
                list.add("୧༼ ヘ ᗜ ヘ ༽୨");
                list.add("༼ ◔ ͜ʖ ◔ ༽");
                list.add("╰༼⇀︿⇀༽つ-]═──");
                list.add("乁༼☯‿☯✿༽ㄏ");
            } else if (selectedIndex == 11) {
                list.add("ㄖꏁㄖ");
                list.add("ᴓᴈᴓ");
                list.add("|°з°|");
                list.add("(ΦзΦ)");
                list.add("˶⚈Ɛ⚈˵");
                list.add("（＿ε＿）");
                list.add("(‘ε’)");
                list.add("⁽˙³˙⁾");
                list.add("(-ε- )");
                list.add("•́ε•̀٥");
                list.add("(☆´3｀)");
                list.add("(・ε・｀)");
                list.add(" Ⴀ͡კႠ͡");
                list.add("(ΘεΘ;)");
                list.add("(≡ε≡；)");
                list.add("（￣ε￣＠）");
                list.add("(´ε｀*)");
                list.add("（*＾3＾）");
                list.add("(*￣з￣)");
                list.add("(○ﾟε^○)");
                list.add("（。ˇ ⊖ˇ）");
                list.add("（○゜ε＾○）");
                list.add("|(￣3￣)|");
                list.add("ヾ(´〓｀)ﾉ");
                list.add("(~￣³￣)~");
                list.add("(ΘεΘʃƪ)");
                list.add("（￣ε￣ʃƪ）");
                list.add("（＠ーεー＠）");
                list.add("(*-(　　)");
                list.add("(๑♡3♡๑)");
            } else if (selectedIndex == 12) {
                list.add("＾ω＾");
                list.add("▼ω▼");
                list.add("(´∀｀）");
                list.add("（＾∀＾）");
                list.add("(^○^)");
                list.add("(｀▽´)");
                list.add("米＾－＾米");
                list.add("(∩_∩)");
                list.add("(⌒∇⌒)");
                list.add("(☆▽☆)");
                list.add("(￣∇￣)");
                list.add("（￣ー+￣）");
                list.add("σ(^○^)");
                list.add("(^■^*)");
                list.add("(*^-^)");
                list.add("d(^^*)");
                list.add("(´w｀*)");
                list.add("|*￣ー￣|");
                list.add("{*≧∀≦}");
                list.add("(o^^o)");
                list.add("(o^∀^)");
                list.add("(*´ー`)");
                list.add("o(^▽^)o");
                list.add("o(^-^)o");
                list.add("(*´∇｀*)");
                list.add("（*´▽`*)");
                list.add("(=^_^=)");
                list.add("σ(ﾟｰ^*)");
                list.add("（●＞ω＜●）");
                list.add("y（^ヮ^）y");
            } else if (selectedIndex == 13) {
                list.add("(खਉख)");
                list.add("(ಡ艸ಡ)");
                list.add("（⌒▽⌒）");
                list.add("（＾ｖ＾）");
                list.add("（＞ｙ＜）");
                list.add("(＾艸＾)");
                list.add("(Ŏ艸Ŏ)");
                list.add("(亝艸亝)");
                list.add("(♡´艸`)");
                list.add("(●´艸`)");
                list.add("(≧艸≦*)");
                list.add("(*>艸<)");
                list.add("( ਊдਊ)");
                list.add("( ´艸｀)");
                list.add("(｡ˇ艸ˇ)");
                list.add("(o>艸<)");
                list.add("(^ц^ )");
                list.add("(☆Θ艸Θ)");
                list.add("（○´艸｀）");
                list.add("(*´艸｀)");
                list.add("（≧ｙ≦＊）");
                list.add("(*・艸・)");
                list.add("（　´∀｀）");
                list.add("(*≧艸≦)");
                list.add("( ╹ਊ╹)");
                list.add("( ՞ਊ՞)");
                list.add("(*´∀｀）");
                list.add("(✪ฺܫ✪ฺ)");
                list.add("( 〃´艸｀)");
                list.add("(❤ฺ￫艸￩)");
            }
        }

        RecyclerView recyclerView = findViewById(R.id.recyclerViewEmoticons);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        EmoticonsAdapter adapter = new EmoticonsAdapter(this);
        recyclerView.setAdapter(adapter);
        if (list != null) adapter.setData(list);
    }
}